# Generated by Django 2.2.2 on 2019-06-22 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_cliente', models.CharField(max_length=40)),
                ('dir_cliente', models.CharField(max_length=100)),
                ('tel_cliente', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('cod_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_empleado', models.CharField(max_length=40)),
                ('pass_empleado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ingrediente_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_ingrediente', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('cod_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('fec_pedido', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('pizza_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_pizza', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMasas',
            fields=[
                ('tipo_Masa_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_tipo', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('cod_registro', models.AutoField(primary_key=True, serialize=False)),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Cliente')),
                ('cod_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Empleado')),
                ('cod_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Hecha_De',
            fields=[
                ('corr_hec_de', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Ingrediente')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pizza')),
                ('tipomasa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.TipoMasas')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Pedido',
            fields=[
                ('corr_det_ped', models.AutoField(primary_key=True, serialize=False)),
                ('cant_pedido', models.IntegerField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pi.Pizza')),
            ],
        ),
    ]
