# Generated by Django 2.2.2 on 2019-06-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0003_auto_20190615_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='nom_pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='precio',
            field=models.FloatField(default='0'),
            preserve_default=False,
        ),
    ]
