# Generated by Django 2.2.2 on 2019-06-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pi', '0004_auto_20190623_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='nom_pizza',
            field=models.CharField(default='pizza', max_length=30),
            preserve_default=False,
        ),
    ]
